# Generated by Django 5.0.1 on 2024-09-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('screenshot', models.ImageField(upload_to='payment_screenshots/')),
                ('amount', models.CharField(max_length=12)),
            ],
        ),
    ]
