# Generated by Django 5.0.1 on 2024-09-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_customdonation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='name',
            field=models.CharField(default='Default Name', max_length=256),
        ),
    ]
