# Generated by Django 5.0.1 on 2024-09-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_couponcode_ticket_coupon_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='couponcode',
            options={'verbose_name': 'Coupon Code', 'verbose_name_plural': 'Coupon Codes'},
        ),
        migrations.AddField(
            model_name='couponcode',
            name='redeemed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
